name: Pre-render and Deploy Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  prerender-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
        
    - name: Update dependencies and config for Cloudflare
      run: |
        # Ensure all files are committed including wrangler.toml
        bun add puppeteer
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update dependencies and Cloudflare config" || echo "No changes"
        git push || echo "No changes to push"